server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.163:3306/tensquare_user?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.0.163
  rabbitmq:
    host: 192.168.0.163
jwt:
  config:
    key: itcast
    ttl: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #部署在服务器上允许跨域访问